### PR TITLE
Rename all camelCase variables to snake_case

### PR DESCRIPTION
**Pull request by ruflin**
This is to adhere to the standard elasticsearch is using

### CODE REVIEW

**Comment by nik9000** [comment]
> This is to to adhere to the standard elasticsearch is using

Its called [snake_case](https://en.wikipedia.org/wiki/Snake_case).

**Comment by nik9000** [comment]
Err, I call it snake_case. And so does that article. I don't mean to speak for everyone on such a controversial subject.

**Comment by ruflin** [comment]
@nik9000 That is the word I was looking for when i wrote the commit message. Thanks. Title renamed.

**Comment by monicasarbu** [comment]
Great. I like more snack_case. I think it fits better with Filebeat and Beats in general.

**Pull request merged**
