### PR TITLE
Added tests for a few encodings

### PR DESCRIPTION
**Pull request by tsg**
Still want to add more encodings, but the approach works very well. The test passes in 0.3 seconds :-).

### CODE REVIEW

**Comment by ruflin** [comment]
:+1: Looks good. Would it be possible to extend the test to it does the initial read and afterwards and append? Like this we make sure for all encodings the readers doesn't break.

**Comment by urso** [comment]
LGTM. Would like to see the test to write the line to file, start filebeat and repeat the text like 2 times to force filebeat tailing

**Comment by tsg** [comment]
I'll add testing append as well. Won't be 0.3 seconds anymore, but oh well.

**Comment by tsg** [comment]
Added more encodings and I'm now also testing for an appended line.

**Pull request merged**
