### PR TITLE
Fix typos in filebeat.yml

### PR DESCRIPTION
**Pull request by 0xfoo**

### CODE REVIEW

**Comment by ruflin** [comment]
@0xfoo Thanks a lot for this contribution. Would you mind to sign the CLA? https://www.elastic.co/contributor-agreement/

**Comment by 0xfoo** [comment]
@ruflin After opening the pull request I saw the CLA, signed it, got an email, confirmed and then got the signed PDF. Not sure if I did something wrong; should the CLA check automatically update?

**Comment by ruflin** [comment]
@0xfoo It should automatically update after your comment. Did you sign it with the same e-mail address you have on Github?

**Comment by 0xfoo** [comment]
Yes I did, but my e-mail addreass was not public (on github). I just changed it, maybe that does the trick.

**Comment by ruflin** [comment]
@0xfoo It should not matter. I just checked manually and it all looks good. Not sure why the system didn't pick it up. I can still merge because of the successful manual check :-)

**Comment by ruflin** [comment]
@0xfoo Merged and thanks again.

**Pull request merged**
