### PR TITLE
Improved filebeat template

### PR DESCRIPTION
**Pull request by ruflin**
Related to issue https://github.com/elastic/filebeat/issues/109

### CODE REVIEW

**Comment by andrewkroh** [comment]
LGTM, but I think it would be good to get a second set of eyes on it.

**Comment by ruflin** [comment]
@monicasarbu I think it would be good if you could have a look if this makes sense.

**Comment by monicasarbu** [comment]
@ruflin The template looks good to me. Did you test it?

**Comment by ruflin** [comment]
@monicasarbu I did some manual tests and I was able to search in the log part as expected.

**Pull request merged**
