### PR TITLE
Fixing typo

### PR DESCRIPTION
**Pull request by rk295**
Timeout was spelt incorrectly.

### CODE REVIEW

**Comment by ruflin** [comment]
@rk295 Thanks a lot for the contribution. We yesterday merged all beats into one repo here (https://github.com/elastic/beats/tree/master/filebeat). Would it be possible for you to open your PR there again?

**Comment by rk295** [comment]
@ruflin no probs, PR sent.

**Comment by ruflin** [comment]
@rk295 Can you link to the PR? not sure I find it.

**Comment by ruflin** [comment]
@rk295 Ah, it was already merged here: https://github.com/elastic/beats/pull/433 Thanks :-)

**Pull request closed without merging**
