### PR TITLE
OS independent code for SafeFileRotate

### PR DESCRIPTION
**Pull request by tsg**
The two windows and !windows versions were similar with the windows version doing an extra move from .filebeat to .filebeat.old. This seems unnecessary and causes the rotation to fail on Win because
.filebeat doesn't exist (.filebeat.new does).

Don't merge yet, i'm still to test on windows.

### CODE REVIEW

**Comment by tsg** [comment]
This doesn't work on windows :-(. Coming up with another solution.

**Comment by driskell** [comment]
On Linux the rename overwrites. On Windows the target can't exist so it needs removing first - but atomicity is lost.

Maybe call `MoveFileEx` directly with `MOVEFILE_REPLACE_EXISTING`.
https://msdn.microsoft.com/en-us/library/windows/desktop/aa365240(v=vs.85).aspx

**Comment by driskell** [comment]
(Assuming that was the problem)

**Comment by tsg** [comment]
@driskell yes, exactly. And right, MoveFileEx would solve the issue if we could call it from Go, which I couldn't find a solution for (that doesn't involve Cgo).

**Comment by tsg** [comment]
I opened #45 with a less elegant and not atomic solution, but that works in my tests.

**Comment by driskell** [comment]
Ah yes, well that explains why I didn't do it in courier!

**Pull request closed without merging**
