### PR TITLE
Improve documentation of scan_frequency. Closes #158

### LINKED ISSUE #158: Improve documentation of scan_frequency
See https://discuss.elastic.co/t/is-a-restart-required-to-see-new-log-files-matching-glob/33192/3

### PR DESCRIPTION
**Pull request by ruflin**

### CODE REVIEW

**Comment by ruflin** [comment]
@dedemorton Can you have a look?

**Comment by dedemorton** [comment]
@ruflin Here are my suggested edits:
Scan frequency specifies how often the prospector checks for new files in the paths that are specified for harvesting. For example, if you specify a glob like  `/var/log/*`, the directory is scanned for files using the frequency specified by scan_frequency.  If you specify 0s, the directory is scanned as frequently as possible. We recommend that you do not specify 0. The default setting is 10s.

**Comment by andrewkroh** [comment]
I updated the PR with @dedemorton's suggestion.

**Comment by ruflin** [comment]
@andrewkroh Thx

**Pull request merged**
